#ifndef UFMOD_CONFIG_H
#define UFMOD_CONFIG_H

/* Feature options */
#ifndef UFMOD_INFO_API_ON
#define UFMOD_INFO_API_ON 1
#endif

#ifndef UFMOD_NOLOOP_ON
#define UFMOD_NOLOOP_ON 1
#endif

#ifndef UFMOD_VOL_CONTROL_ON
#define UFMOD_VOL_CONTROL_ON 1
#endif

#ifndef UFMOD_JUMP_TO_PAT_ON
#define UFMOD_JUMP_TO_PAT_ON 1
#endif

/* Special engine flags */
#ifndef UFMOD_INSTRUMENTVIBRATO_ON
#define UFMOD_INSTRUMENTVIBRATO_ON 1
#endif

#ifndef UFMOD_VOLUMEENVELOPE_ON
#define UFMOD_VOLUMEENVELOPE_ON 1
#endif

#ifndef UFMOD_PANENVELOPE_ON
#define UFMOD_PANENVELOPE_ON 1
#endif

#ifndef UFMOD_VOLUMEBYTE_ON
#define UFMOD_VOLUMEBYTE_ON 1
#endif

#ifndef UFMOD_ADPCM_ON
#define UFMOD_ADPCM_ON 1
#endif

#ifndef UFMOD_AMIGAPERIODS_ON
#define UFMOD_AMIGAPERIODS_ON 1
#endif

/* Hardware voice persistence for looping samples */
#ifndef UFMOD_PERSIST_LOOPING_VOICES_ON
#define UFMOD_PERSIST_LOOPING_VOICES_ON 1
#endif

/* XM effects */
#ifndef UFMOD_ARPEGGIO_ON
#define UFMOD_ARPEGGIO_ON 1
#endif

#ifndef UFMOD_PORTAUP_ON
#define UFMOD_PORTAUP_ON 1
#endif

#ifndef UFMOD_PORTADOWN_ON
#define UFMOD_PORTADOWN_ON 1
#endif

#ifndef UFMOD_PORTATO_ON
#define UFMOD_PORTATO_ON 1
#endif

#ifndef UFMOD_VIBRATO_ON
#define UFMOD_VIBRATO_ON 1
#endif

#ifndef UFMOD_PORTATOVOLSLIDE_ON
#define UFMOD_PORTATOVOLSLIDE_ON 1
#endif

#ifndef UFMOD_VIBRATOVOLSLIDE_ON
#define UFMOD_VIBRATOVOLSLIDE_ON 1
#endif

#ifndef UFMOD_TREMOLO_ON
#define UFMOD_TREMOLO_ON 1
#endif

#ifndef UFMOD_SETPANPOSITION_ON
#define UFMOD_SETPANPOSITION_ON 1
#endif

#ifndef UFMOD_SETSAMPLEOFFSET_ON
#define UFMOD_SETSAMPLEOFFSET_ON 1
#endif

#ifndef UFMOD_VOLUMESLIDE_ON
#define UFMOD_VOLUMESLIDE_ON 1
#endif

#ifndef UFMOD_PATTERNJUMP_ON
#define UFMOD_PATTERNJUMP_ON 1
#endif

#ifndef UFMOD_SETVOLUME_ON
#define UFMOD_SETVOLUME_ON 1
#endif

#ifndef UFMOD_PATTERNBREAK_ON
#define UFMOD_PATTERNBREAK_ON 1
#endif

#ifndef UFMOD_SETSPEED_ON
#define UFMOD_SETSPEED_ON 1
#endif

#ifndef UFMOD_SETGLOBALVOLUME_ON
#define UFMOD_SETGLOBALVOLUME_ON 1
#endif

#ifndef UFMOD_GLOBALVOLSLIDE_ON
#define UFMOD_GLOBALVOLSLIDE_ON 1
#endif

#ifndef UFMOD_KEYOFF_ON
#define UFMOD_KEYOFF_ON 1
#endif

#ifndef UFMOD_SETENVELOPEPOS_ON
#define UFMOD_SETENVELOPEPOS_ON 1
#endif

#ifndef UFMOD_PANSLIDE_ON
#define UFMOD_PANSLIDE_ON 1
#endif

#ifndef UFMOD_MULTIRETRIG_ON
#define UFMOD_MULTIRETRIG_ON 1
#endif

#ifndef UFMOD_TREMOR_ON
#define UFMOD_TREMOR_ON 1
#endif

#ifndef UFMOD_EXTRAFINEPORTA_ON
#define UFMOD_EXTRAFINEPORTA_ON 1
#endif

#ifndef UFMOD_FINEPORTAUP_ON
#define UFMOD_FINEPORTAUP_ON 1
#endif

#ifndef UFMOD_FINEPORTADOWN_ON
#define UFMOD_FINEPORTADOWN_ON 1
#endif

#ifndef UFMOD_SETVIBRATOWAVE_ON
#define UFMOD_SETVIBRATOWAVE_ON 1
#endif

#ifndef UFMOD_SETFINETUNE_ON
#define UFMOD_SETFINETUNE_ON 1
#endif

#ifndef UFMOD_PATTERNLOOP_ON
#define UFMOD_PATTERNLOOP_ON 1
#endif

#ifndef UFMOD_SETTREMOLOWAVE_ON
#define UFMOD_SETTREMOLOWAVE_ON 1
#endif

#ifndef UFMOD_SETPANPOSITION16_ON
#define UFMOD_SETPANPOSITION16_ON 1
#endif

#ifndef UFMOD_RETRIG_ON
#define UFMOD_RETRIG_ON 1
#endif

#ifndef UFMOD_NOTECUT_ON
#define UFMOD_NOTECUT_ON 1
#endif

#ifndef UFMOD_NOTEDELAY_ON
#define UFMOD_NOTEDELAY_ON 1
#endif

#ifndef UFMOD_PATTERNDELAY_ON
#define UFMOD_PATTERNDELAY_ON 1
#endif

/* Derived / compound flags matching eff.inc */
#ifndef UFMOD_PORTAUP_OR_DOWN_ON
#define UFMOD_PORTAUP_OR_DOWN_ON (UFMOD_PORTAUP_ON || UFMOD_PORTADOWN_ON)
#endif

#ifndef UFMOD_VIBRATO_OR_VOLSLIDE
#define UFMOD_VIBRATO_OR_VOLSLIDE (UFMOD_VIBRATO_ON || UFMOD_VOLUMESLIDE_ON)
#endif

#ifndef UFMOD_VIBRATO_OR_TREMOLO
#define UFMOD_VIBRATO_OR_TREMOLO (UFMOD_VIBRATO_ON || UFMOD_TREMOLO_ON)
#endif

#ifndef UFMOD_PORTATO_OR_VOLSLIDE
#define UFMOD_PORTATO_OR_VOLSLIDE (UFMOD_PORTATO_ON || UFMOD_VOLUMESLIDE_ON)
#endif

#ifndef UFMOD_VOLUME_OR_PANENVELOPE
#define UFMOD_VOLUME_OR_PANENVELOPE (UFMOD_VOLUMEENVELOPE_ON || UFMOD_PANENVELOPE_ON)
#endif

#ifndef UFMOD_GLOBALVOL_ON
#define UFMOD_GLOBALVOL_ON (UFMOD_SETGLOBALVOLUME_ON || UFMOD_GLOBALVOLSLIDE_ON)
#endif

#ifndef UFMOD_FINEVOLUMESLIDE_ON
#define UFMOD_FINEVOLUMESLIDE_ON 1
#endif

#endif
